/**
 * Boilerplate Generator - Transform engine for customizing templates
 * Handles placeholder replacement, file customization, and env generation
 */

export interface StackConfig {
  database: 'supabase' | 'mongodb';
  payments: 'lemonsqueezy' | 'stripe';
  emails: 'resend' | 'mailgun';
  authProviders: string[];
}

export interface ProjectConfig {
  projectName: string;
  displayName: string;
  description: string;
  idea: string;
  answers: Record<string, string>;
  stack: StackConfig;
}

// Default stack configuration
export const DEFAULT_STACK: StackConfig = {
  database: 'supabase',
  payments: 'lemonsqueezy',
  emails: 'resend',
  authProviders: ['magic-link', 'google'],
};

/**
 * Placeholder mappings for template files
 */
const PLACEHOLDERS = {
  '{{PROJECT_NAME}}': (config: ProjectConfig) => config.projectName,
  '{{DISPLAY_NAME}}': (config: ProjectConfig) => config.displayName,
  '{{PROJECT_DESCRIPTION}}': (config: ProjectConfig) => config.description,
  '{{DATABASE}}': (config: ProjectConfig) => config.stack.database,
  '{{PAYMENT_PROVIDER}}': (config: ProjectConfig) => config.stack.payments,
  '{{EMAIL_PROVIDER}}': (config: ProjectConfig) => config.stack.emails,
  '{{AUTH_PROVIDERS}}': (config: ProjectConfig) => config.stack.authProviders.join(', '),
  '{{YEAR}}': () => new Date().getFullYear().toString(),
  '{{GENERATED_DATE}}': () => new Date().toISOString().split('T')[0],
} as const;

/**
 * Apply placeholder replacements to content
 */
export function applyPlaceholders(content: string, config: ProjectConfig): string {
  let result = content;
  
  for (const [placeholder, getValue] of Object.entries(PLACEHOLDERS)) {
    const value = getValue(config);
    result = result.replace(new RegExp(escapeRegex(placeholder), 'g'), value);
  }
  
  return result;
}

/**
 * Escape special regex characters
 */
function escapeRegex(str: string): string {
  return str.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
}

/**
 * Generate .env.example content based on stack configuration
 */
export function generateEnvExample(config: ProjectConfig): string {
  const lines: string[] = [
    '# Generated by Coding Kickstarter',
    `# Project: ${config.displayName}`,
    `# Generated: ${new Date().toISOString()}`,
    '',
    '# ===================',
    '# App Configuration',
    '# ===================',
    'NEXT_PUBLIC_APP_URL=http://localhost:3000',
    `NEXT_PUBLIC_APP_NAME="${config.displayName}"`,
    '',
  ];

  // Database configuration
  lines.push('# ===================');
  lines.push('# Database');
  lines.push('# ===================');
  
  if (config.stack.database === 'supabase') {
    lines.push('# Supabase - https://supabase.com/dashboard');
    lines.push('NEXT_PUBLIC_SUPABASE_URL=your-supabase-url');
    lines.push('NEXT_PUBLIC_SUPABASE_ANON_KEY=your-supabase-anon-key');
    lines.push('SUPABASE_SERVICE_ROLE_KEY=your-supabase-service-role-key');
  } else {
    lines.push('# MongoDB - https://cloud.mongodb.com');
    lines.push('MONGODB_URI=mongodb+srv://username:password@cluster.mongodb.net/dbname');
  }
  lines.push('');

  // Authentication
  lines.push('# ===================');
  lines.push('# Authentication (NextAuth v5)');
  lines.push('# ===================');
  lines.push('# Generate with: openssl rand -base64 32');
  lines.push('AUTH_SECRET=your-auth-secret-min-32-chars');
  lines.push('AUTH_URL=http://localhost:3000');
  lines.push('');
  
  if (config.stack.authProviders.includes('google')) {
    lines.push('# Google OAuth - https://console.cloud.google.com');
    lines.push('AUTH_GOOGLE_ID=your-google-client-id');
    lines.push('AUTH_GOOGLE_SECRET=your-google-client-secret');
    lines.push('');
  }
  
  if (config.stack.authProviders.includes('github')) {
    lines.push('# GitHub OAuth - https://github.com/settings/developers');
    lines.push('AUTH_GITHUB_ID=your-github-client-id');
    lines.push('AUTH_GITHUB_SECRET=your-github-client-secret');
    lines.push('');
  }

  // Payments
  lines.push('# ===================');
  lines.push('# Payments');
  lines.push('# ===================');
  
  if (config.stack.payments === 'lemonsqueezy') {
    lines.push('# Lemon Squeezy - https://app.lemonsqueezy.com/settings/api');
    lines.push('LEMONSQUEEZY_API_KEY=your-lemonsqueezy-api-key');
    lines.push('LEMONSQUEEZY_STORE_ID=your-store-id');
    lines.push('LEMONSQUEEZY_WEBHOOK_SECRET=your-webhook-secret');
  } else {
    lines.push('# Stripe - https://dashboard.stripe.com/apikeys');
    lines.push('STRIPE_SECRET_KEY=sk_test_xxx');
    lines.push('NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY=pk_test_xxx');
    lines.push('STRIPE_WEBHOOK_SECRET=whsec_xxx');
  }
  lines.push('');

  // Email
  lines.push('# ===================');
  lines.push('# Email');
  lines.push('# ===================');
  
  if (config.stack.emails === 'resend') {
    lines.push('# Resend - https://resend.com/api-keys');
    lines.push('RESEND_API_KEY=re_xxx');
    lines.push('EMAIL_FROM=onboarding@resend.dev');
  } else {
    lines.push('# Mailgun - https://app.mailgun.com/app/account/security/api_keys');
    lines.push('MAILGUN_API_KEY=your-mailgun-api-key');
    lines.push('MAILGUN_DOMAIN=your-domain.com');
    lines.push('EMAIL_FROM=hello@your-domain.com');
  }
  lines.push('');

  return lines.join('\n');
}

/**
 * Generate README.md content based on project configuration
 */
export function generateReadme(config: ProjectConfig): string {
  const stackBadges = [
    `![Next.js](https://img.shields.io/badge/Next.js-16-black?logo=next.js)`,
    `![React](https://img.shields.io/badge/React-19-61dafb?logo=react)`,
    `![TypeScript](https://img.shields.io/badge/TypeScript-5-3178c6?logo=typescript)`,
  ];

  if (config.stack.database === 'supabase') {
    stackBadges.push(`![Supabase](https://img.shields.io/badge/Supabase-Database-3ecf8e?logo=supabase)`);
  } else {
    stackBadges.push(`![MongoDB](https://img.shields.io/badge/MongoDB-Database-47a248?logo=mongodb)`);
  }

  if (config.stack.payments === 'lemonsqueezy') {
    stackBadges.push(`![Lemon Squeezy](https://img.shields.io/badge/Lemon_Squeezy-Payments-ffc233)`);
  } else {
    stackBadges.push(`![Stripe](https://img.shields.io/badge/Stripe-Payments-635bff?logo=stripe)`);
  }

  return `# ${config.displayName}

${stackBadges.join(' ')}

${config.description}

> 🚀 Generated by [Coding Kickstarter](https://codingkickstarter.vercel.app)

## Tech Stack

- **Framework**: Next.js 16 + React 19 (App Router)
- **Database**: ${config.stack.database === 'supabase' ? 'Supabase' : 'MongoDB'}
- **Auth**: NextAuth v5 (${config.stack.authProviders.join(', ')})
- **Payments**: ${config.stack.payments === 'lemonsqueezy' ? 'Lemon Squeezy' : 'Stripe'}
- **Emails**: ${config.stack.emails === 'resend' ? 'Resend' : 'Mailgun'}
- **UI**: Shadcn/ui + Tailwind CSS

## Getting Started

### Prerequisites

- Node.js 18.17+
- npm/yarn/pnpm
${config.stack.database === 'supabase' ? '- Supabase account' : '- MongoDB Atlas account'}

### Installation

1. Clone this repository:
   \`\`\`bash
   git clone https://github.com/YOUR_USERNAME/${config.projectName}.git
   cd ${config.projectName}
   \`\`\`

2. Install dependencies:
   \`\`\`bash
   npm install
   \`\`\`

3. Set up environment variables:
   \`\`\`bash
   cp .env.example .env.local
   \`\`\`
   
   Then fill in your API keys in \`.env.local\`

4. Run the development server:
   \`\`\`bash
   npm run dev
   \`\`\`

5. Open [http://localhost:3000](http://localhost:3000)

## Project Structure

\`\`\`
├── app/
│   ├── (marketing)/     # Public pages (landing, pricing)
│   ├── (app)/           # Protected app pages
│   │   └── dashboard/   # User dashboard
│   └── api/             # API routes
│       ├── auth/        # NextAuth routes
│       └── webhooks/    # Payment webhooks
├── components/
│   └── ui/              # Shadcn components
├── lib/
│   ├── auth.ts          # Auth configuration
│   ├── db.ts            # Database client
│   └── payments.ts      # Payment processing
├── actions/             # Server actions
├── emails/              # Email templates
└── types/               # TypeScript types
\`\`\`

## Environment Variables

Copy \`.env.example\` to \`.env.local\` and configure:

| Variable | Description |
|----------|-------------|
| \`NEXT_PUBLIC_APP_URL\` | Your app URL |
${config.stack.database === 'supabase' ? '| `NEXT_PUBLIC_SUPABASE_URL` | Supabase project URL |\n| `NEXT_PUBLIC_SUPABASE_ANON_KEY` | Supabase anonymous key |' : '| `MONGODB_URI` | MongoDB connection string |'}
| \`AUTH_SECRET\` | NextAuth secret (32+ chars) |
${config.stack.payments === 'lemonsqueezy' ? '| `LEMONSQUEEZY_API_KEY` | Lemon Squeezy API key |' : '| `STRIPE_SECRET_KEY` | Stripe secret key |'}
${config.stack.emails === 'resend' ? '| `RESEND_API_KEY` | Resend API key |' : '| `MAILGUN_API_KEY` | Mailgun API key |'}

## Scripts

| Command | Description |
|---------|-------------|
| \`npm run dev\` | Start development server |
| \`npm run build\` | Build for production |
| \`npm run start\` | Start production server |
| \`npm run lint\` | Run ESLint |

## Deployment

### Vercel (Recommended)

[![Deploy with Vercel](https://vercel.com/button)](https://vercel.com/new/clone?repository-url=https://github.com/YOUR_USERNAME/${config.projectName})

1. Push to GitHub
2. Import to Vercel
3. Add environment variables
4. Deploy!

## License

MIT © ${new Date().getFullYear()}

---

Built with ❤️ using [Coding Kickstarter](https://codingkickstarter.vercel.app)
`;
}

/**
 * Generate .cursorrules file content
 */
export function generateCursorRules(config: ProjectConfig): string {
  return `You are editing a production-ready Next.js SaaS boilerplate.

## Critical Rules
- DO NOT remove authentication, payment, or environment systems
- DO NOT modify lib/auth.ts or lib/payments.ts unless explicitly asked
- Preserve code stability over creativity
- Prioritize correctness and build integrity

## Project Context
- Project: ${config.displayName}
- Framework: Next.js 16 + React 19 (App Router)
- Auth: NextAuth v5 with ${config.stack.authProviders.join(', ')}
- Database: ${config.stack.database === 'supabase' ? 'Supabase' : 'MongoDB'}
- Payments: ${config.stack.payments === 'lemonsqueezy' ? 'Lemon Squeezy' : 'Stripe'}
- Emails: ${config.stack.emails === 'resend' ? 'Resend' : 'Mailgun'}
- UI: Shadcn/ui (new-york style)

## Safe to Modify
- app/(app)/* - App pages and features
- components/* (except auth/payment components)
- actions/* - Server actions
- Any new files you create

## Protected Files (Ask Before Changing)
- lib/auth.ts - Authentication configuration
- lib/payments.ts - Payment processing
- lib/db.ts - Database client
- app/api/auth/* - Auth API routes
- app/api/webhooks/* - Payment webhooks
- .env.example - Environment template

## When Adding Features
1. Use existing UI components from components/ui/
2. Follow the established folder structure
3. Add new routes under app/(app)/
4. Create server actions in actions/
5. Add types to types/

## Code Style
- Use TypeScript strict mode
- Prefer async/await over promises
- Use server actions for mutations
- Keep components small and focused
- Add proper error handling
`;
}

/**
 * Generate package.json content
 */
export function generatePackageJson(config: ProjectConfig): string {
  const pkg = {
    name: config.projectName,
    version: '0.1.0',
    private: true,
    scripts: {
      dev: 'next dev',
      build: 'next build',
      start: 'next start',
      lint: 'next lint',
    },
    dependencies: {
      'next': '16.0.0',
      'react': '19.2.0',
      'react-dom': '19.2.0',
      'next-auth': '^5.0.0-beta.25',
      'class-variance-authority': '^0.7.1',
      'clsx': '^2.1.1',
      'tailwind-merge': '^3.4.0',
      'lucide-react': '^0.548.0',
      'zod': '^3.25.0',
      '@radix-ui/react-slot': '^1.2.4',
    } as Record<string, string>,
    devDependencies: {
      '@types/node': '^20',
      '@types/react': '^19',
      '@types/react-dom': '^19',
      'typescript': '^5',
      'tailwindcss': '^3.4.18',
      'postcss': '^8.5.0',
      'autoprefixer': '^10.4.21',
      'eslint': '^9',
      'eslint-config-next': '16.0.0',
    },
  };

  // Add database-specific dependencies
  if (config.stack.database === 'supabase') {
    pkg.dependencies['@supabase/supabase-js'] = '^2.76.0';
    pkg.dependencies['@supabase/ssr'] = '^0.6.0';
  } else {
    pkg.dependencies['mongodb'] = '^6.12.0';
  }

  // Add payment-specific dependencies
  if (config.stack.payments === 'lemonsqueezy') {
    pkg.dependencies['@lemonsqueezy/lemonsqueezy.js'] = '^3.4.0';
  } else {
    pkg.dependencies['stripe'] = '^17.0.0';
    pkg.dependencies['@stripe/stripe-js'] = '^5.0.0';
  }

  // Add email-specific dependencies
  if (config.stack.emails === 'resend') {
    pkg.dependencies['resend'] = '^4.0.0';
    pkg.dependencies['@react-email/components'] = '^0.0.30';
  } else {
    pkg.dependencies['mailgun.js'] = '^10.2.0';
  }

  return JSON.stringify(pkg, null, 2);
}

/**
 * Get all files that need to be customized for the project
 */
export function getCustomizedFiles(config: ProjectConfig): Array<{ path: string; content: string }> {
  return [
    { path: '.env.example', content: generateEnvExample(config) },
    { path: 'README.md', content: generateReadme(config) },
    { path: '.cursorrules', content: generateCursorRules(config) },
    { path: 'package.json', content: generatePackageJson(config) },
  ];
}

/**
 * Validate project name
 */
export function validateProjectName(name: string): { valid: boolean; error?: string } {
  if (!name || name.trim().length === 0) {
    return { valid: false, error: 'Project name is required' };
  }
  
  if (name.length > 100) {
    return { valid: false, error: 'Project name must be 100 characters or less' };
  }
  
  // Check for valid characters (will be sanitized, but warn about major issues)
  if (/^[0-9-]/.test(name)) {
    return { valid: false, error: 'Project name cannot start with a number or hyphen' };
  }
  
  return { valid: true };
}

/**
 * Generate a display name from project name
 */
export function generateDisplayName(projectName: string): string {
  return projectName
    .split('-')
    .map(word => word.charAt(0).toUpperCase() + word.slice(1))
    .join(' ');
}

/**
 * Create a project configuration from user inputs
 */
export function createProjectConfig(
  projectName: string,
  idea: string,
  answers: Record<string, string>,
  stack: Partial<StackConfig> = {}
): ProjectConfig {
  const sanitizedName = projectName
    .toLowerCase()
    .trim()
    .replace(/[^a-z0-9-]/g, '-')
    .replace(/-+/g, '-')
    .replace(/^-|-$/g, '')
    .substring(0, 100);

  return {
    projectName: sanitizedName,
    displayName: generateDisplayName(sanitizedName),
    description: idea.slice(0, 200),
    idea,
    answers,
    stack: {
      ...DEFAULT_STACK,
      ...stack,
    },
  };
}

